include: package:lints/recommended.yaml

analyzer:
  strong-mode:
    implicit-casts: false
  exclude:
    - "build/**"
    - "doc/api/**"
    - "last_prod/**"
    - "lib/bower/**"
    - "lib/src/protos/**"
    - "third_party/pkg/**"
    - "web/example/workshops/**"
linter:
  rules:
    - always_declare_return_types
    - avoid_private_typedef_functions
    - directives_ordering
    - prefer_final_in_for_each
    - prefer_final_locals
    - prefer_mixin
    - prefer_relative_imports
    - prefer_single_quotes
    - sort_pub_dependencies
    - unawaited_futures
